apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
    kafka.config: |
      # Kafka
      {{- if .Values.kafka.producer.config }}
      {{- .Values.kafka.producer.config | nindent 6 }}
      {{- end -}}
      {{- if not .Values.kafka.producer.config }}
      bootstrap.servers=localhost:9092
      {{- end }}