{{- if .Values.kafka.producer.ccloud }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-kafka-secret
type: Opaque
data:
  clusterApiKey: {{ .Values.kafka.producer.ccloud.key }}
  clusterApiSecret: {{ .Values.kafka.producer.ccloud.secret }}
{{- end -}}

