{{- if .Values.crypto }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-encryption-secret
type: Opaque
data:
  cryptoKey: {{ .Values.crypto.key }}
  cryptoIv: {{ .Values.crypto.iv }}
{{- end -}}